Working snap created
noahgorstein/jqp pull request #117
Opened 2024-08-27 16:53 UTC by kz6fittycent

Hi,

I've recently created a snap for `jqp` and have it working with strict confinement. Meaning it will run "as native" within a snap container for any Linux distro supporting `snapd`. Learn more about snaps [here](https://snapcraft.io/about).

I am happy to maintain the snap for your project, unless you'd prefer maintaining it all "in-house". There's not much anyone on the team would have to do, as the snaps are automatically built and published on the snap [store](https://snapcraft.io/store).

As part of the security checks, pedigree, and validation, the upstream team/devs should at least know about it and agree with the publication of the snap. Basically, the snap will much like a `.deb` or `.rpm` on another distro supporting those packages; except it's distro agnostic.

I hope this comes as a welcome PR. 

New files:

- Snapcraft yaml
- GH Workflow - test-snap-can-build
- Updated README with snap instructions

2024-08-31 20:09 UTC, noahgorstein requested changes
Hey @kz6fittycent - thanks for your contribution! 

I'm happy to let you maintain the snap for jqp. 

if you don't mind just cleaning up the typo in the readme, I'll merge it after that.

2024-09-05 15:14 UTC, kz6fittycent commented
Thanks @noahgorstein I need to add that workflow to my own repos! I can't tell you how many times I've missed typos.

2024-09-06 18:26 UTC, kz6fittycent commented
The snap has been published! Thanks for working w/ me on this.

2024-09-12 16:20 UTC, noahgorstein approved these changes

2024-09-12 16:20 UTC, merged