config: option for overrides to chroma styles
noahgorstein/jqp pull request #32
Opened 2022-10-12 03:28 UTC by ktprograms

User facing changes:
- Remove file option from config
- Move theme option to theme.name
- Add theme.chromaStyleOverrides map for style overrides

Code changes:
- Copy code from quick.Highlight to use chroma.Style object instead of looking up by name
- Pass chroma.Style pointer instead of object as chroma Format requires style pointer

2022-10-13 03:47 UTC, noahgorstein commented
Thanks for your PR @ktprograms. I'll be out of town without my computer for about a week but will try to get to this when I'm back later next week. Cheers.

2022-10-28 01:43 UTC, noahgorstein requested changes
This looks and works great @ktprograms. Small typo in the README but good to go otherwise. Thanks again for your contribution and apologies for just getting around to review this.

2022-10-28 01:43 UTC, noahgorstein commented on README.md
> +  name" "monokai" # name is required to know which theme to override
```suggestion
  name: "monokai" # name is required to know which theme to override
```

2022-10-28 10:49 UTC, ktprograms commented on README.md
> +  name" "monokai" # name is required to know which theme to override
Oops, fixed (and also rebased on `main`)

2023-01-07 22:27 UTC, noahgorstein approved these changes

2023-01-07 22:30 UTC, merged