code review
noahgorstein/jqp pull request #61
Opened 2024-05-07 19:47 UTC by ccoVeille

- **chore: format file with gofumpt before working on them**
- **chore: fix import order by running gci**
- **chore: use JSON acronym everywhere**
- **chore: replace deprecated method**
- **chore: avoid variable shadowing import**
- **chore: remove useless code**
- **chore: small refactoring**
- **fix: handle all possible errors**

2024-05-07 19:48 UTC, ccoVeille commented
Please accept my code review.

I used golangci-lint to spot a lot of small design issues.

If you are OK, I could also add golangci-lint GitHub actions to your project

2024-05-08 21:26 UTC, noahgorstein commented
Thanks for your contribution - should have some time to look at this later this week/over the weekend!

2024-05-09 03:16 UTC, ccoVeille commented
OK, no problem.

2024-05-09 21:41 UTC, noahgorstein requested changes
Overall looks great - really appreciate this PR and all your others. Just 2 questions for you.

 I kind of hacked this tool together as you can see :D and don't primarily work in Go so appreciate all the tips on linting, style, organization, control flow, etc.

2024-05-09 21:41 UTC, noahgorstein commented on cmd/utils.go
> +		return nil, fmt.Errorf("Unable to open file: %w", e)
Should the `"U"` in `"Unable"` also be lower case to be consistent?

2024-05-09 21:41 UTC, noahgorstein commented on tui/bubbles/jqplayground/commands.go
> +		err := os.WriteFile(b.fileselector.GetInput(), []byte(b.results), 0o644)
Should `0o644` be `0644`?

2024-05-09 22:14 UTC, ccoVeille commented on tui/bubbles/jqplayground/commands.go
> +		err := os.WriteFile(b.fileselector.GetInput(), []byte(b.results), 0o644)
gofumpt (better go fmt with a tendentious name) is responsible for that

0644 is in fact octal, otherwise we would have written 644, the sticky bit is provided but set to 0

In Go, the octal is prefixed with 0x

That's why gofumpt enforces it

2024-05-09 22:15 UTC, ccoVeille commented on cmd/utils.go
> +		return nil, fmt.Errorf("Unable to open file: %w", e)
It should. But I didn't change everything. Also I might have missed a few thjngs

2024-05-09 22:16 UTC, ccoVeille commented on cmd/utils.go
> +		return nil, fmt.Errorf("Unable to open file: %w", e)
Not a real problem to leave it like that

2024-05-10 19:46 UTC, noahgorstein approved these changes

2024-05-10 19:48 UTC, merged